### ISSUE TITLE
Subject display issue in CS 2.0.0-RC2

### ISSUE THREAD

**Issue by mjb12** [NrgXnat/container-service#7]
When opening a project I get two Exception alerts with the following messages:

- window.available_elements_getByName is not a function
- Cannot read property 'length' of null

and these log entries in Chrome dev console:

![chrome console](https://user-images.githubusercontent.com/14131403/44112262-3eaae852-9fca-11e8-82a3-a71b0ec85887.PNG)

After dismissing the alert modals the page loads and functions fine with the except of my Subjects list being empty.  Clicking the Reload button on the Subjects list causes the error pop-ups to repeat as does removing the Subjects tab and re-adding it.

This issue is not present in releases 2.0.0-RC1 or 1.5.1 of the Container Service plugin.

Versions of other potentially relevant bits:
Tomcat: 7.0.90
Java: 1.7.0_181
XNAT: 1.7.4.1, build 1408
Contain Service plugin: 2.0.0-RC2
Selectable Table: 1.0.0

**Comment by johnflavin** [comment]
Thanks for pointing this out. I didn't respond right away because we had an internal debate about what to do with this. The fundamental problem is that container service 2.0.0 is meant to be compatible with XNAT 1.7.5. You've encountered an incompatibility with earlier XNAT versions.

I had hoped we could keep CS 2.0.0 mostly backwards compatible with earlier XNAT versions. In the backend code, there isn't much that was changed that requires 1.7.5. If you tried to use any of the new 1.7.5-only features, you'd get errors, but things would mostly work the same as they had before. However, I hadn't anticipated the UI changes. There have been a (to me unknown) number of changes to the CS UI that were made necessary by XNAT 1.7.5 changes. This error you’re seeing is caused by code that has been updated in CS, but not in your 1.7.4.1 XNAT.

What we decided to do is split the recent CS development code into two branches, one that does not depend on anything in XNAT 1.7.5 and one that does. I intend to release these two branches simultaneously as CS 1.5.2, which is compatible with pre-1.7.5 XNATs, and CS 2.0.0, which is compatible with post-1.7.5 XNATs, respectively.

My possibly naïve hope is that CS 1.5.2 will _also_ be compatible with XNAT 1.7.5, but just won't have the new features that will only be in 2.0.0. But we would need to do some testing to verify that is possible.

Again, thanks for trying out the new version and reporting the bug.
